# Generated by Django 2.2.5 on 2019-10-03 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_summarization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizedText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_text', models.TextField(default=None)),
                ('summarized_text', models.TextField(default=None)),
                ('summarized_text_length_in_percentage', models.FloatField(default=None)),
                ('number_of_summarized_sentences', models.IntegerField(default=None)),
                ('text_category', models.CharField(default=None, max_length=40)),
                ('text_title', models.CharField(default=None, max_length=500)),
                ('is_saved', models.BinaryField(default=0)),
                ('datetime_of_creation', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
