# Generated by Django 2.2.5 on 2019-11-03 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_summarization', '0002_summarizedtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizedtext',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
