# Generated by Django 2.2.5 on 2019-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_summarization', '0003_auto_20191103_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizedtext',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
