# Generated by Django 2.2.5 on 2019-12-08 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_summarization', '0004_auto_20191208_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarizedtext',
            name='is_saved',
        ),
        migrations.RemoveField(
            model_name='summarizedtext',
            name='summarized_text_length_in_percentage',
        ),
        migrations.RemoveField(
            model_name='summarizedtext',
            name='text_category',
        ),
        migrations.RemoveField(
            model_name='summarizedtext',
            name='text_title',
        ),
        migrations.RemoveField(
            model_name='summarizedtext',
            name='user_id',
        ),
        migrations.AddField(
            model_name='summarizedtext',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='summarizedtext',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
