# Generated by Django 2.2.5 on 2019-12-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_summarization', '0005_auto_20191208_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarizedtext',
            name='word_difference',
            field=models.IntegerField(default=None),
        ),
    ]
