# Generated by Django 2.2.5 on 2019-12-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_summarization', '0006_summarizedtext_word_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizedtext',
            name='word_difference',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
