# Generated by Django 2.2.5 on 2020-04-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0005_auto_20200404_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedtext',
            old_name='full_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='savedtext',
            old_name='summarized_text',
            new_name='text_hash',
        ),
    ]
