# Generated by Django 2.2.5 on 2020-04-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0006_auto_20200405_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedtext',
            old_name='text',
            new_name='text_json',
        ),
        migrations.AddField(
            model_name='savedtext',
            name='main_indexes',
            field=models.TextField(default=None),
        ),
    ]
