# Generated by Django 2.2.5 on 2020-04-19 14:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0008_auto_20200419_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtext',
            name='datetime_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 14, 57, 6, 929028)),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
