# Generated by Django 2.2.5 on 2020-04-19 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0009_auto_20200419_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtext',
            name='datetime_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 16, 39, 53, 757049)),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='chat_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
